### PR TITLE
Add real player texture and convex shape

### PR DESCRIPTION
**Pull request by Noviv**

### CODE REVIEW

**Review by shraymittal — APPROVED** [review]
It handles well and looks good, but if we're doing a human player does attack of the geometry really make sense?

**Comment by Noviv** [comment]
> It handles well and looks good, but if we're doing a human player does attack of the geometry really make sense?

Not sure, I just figured it could be a human vs geometry? I don't think we care about storyline or logic much right now. I was just really excited about the automatic generation of the collision shape.

**Comment by shraymittal** [comment]
> > It handles well and looks good, but if we're doing a human player does attack of the geometry really make sense?
> 
> Not sure, I just figured it could be a human vs geometry? I don't think we care about storyline or logic much right now. I was just really excited about the automatic generation of the collision shape.

alright, I approved I think it's fine to merge if you want to, I just think like a spaceship or an airplane or smth makes more sense here

**Comment by Noviv** [comment]
Using sprites from http://millionthvector.blogspot.com/p/free-sprites.html

**Pull request merged**
